### ISSUE TITLE
Does not compile in IntelliJ IDEA

### ISSUE THREAD

**Issue by ederancz** [SainsburyWellcomeCentre/aMAP#1]
Arrow is greyed out. 
If trying to compile in command line with mvn, moans that "No goal has been specified for this build.".
On a side note, Wiki page install instructions seem to related to another (already compiled) version?

**Comment by cniedwor** [comment]
Interesting, I didn't know that the lack of a default goal would also annoy IntelliJ - should be fixed now. And yes, there is a link for a precompiled version on the wiki page, which is what it's referring to.

**Comment by ederancz** [comment]
Compiles fine now, thanks for fixing this!

**Comment by ederancz** [comment]
errr, 
rancze@bigmac1:~/Documents/GitHub/aMAP/target$ java -jar aMAP-0.0.1.jar 
no main manifest attribute, in aMAP-0.0.1.jar

edit: however, the binary works fine, just run the test brain and all went smoothly. 
Is the current version significantly improved / different compared to the binary?

**Comment by cniedwor** [comment]
There should be no difference between the binary and this version, nevertheless, the thing should compile.
Anyway, I found the issue, due to a superfluos <pluginmanagement> tag some of the maven plugins did actually not run. Unfortunately that included the plugin that generates the proper .jar file. When you build now you should get a ...jar-with-dependencies.jar which is the one that runs. Also, it will generate a .tar.gz that includes the niftyreg binaries, so that is the version you actually download from the wiki. Please close if it works for you :)

**Comment by ederancz** [comment]
yep, it runs, thanks!
